remove omiteempty for SelectMenu MinValues
bwmarrin/discordgo pull request #1052
Opened 2021-12-11 05:04 UTC by plally

0 is valid for MinValues, it can be used to allow a user to remove options on a select menu that defaults to having items selected

this would change the behavior of the SelectMenu component, instead of default to `1` (this is what discord defaults to if you dont provide a MinValues) it would default to 0 because we would always be passing min_values to discord. If this is not desirable I could instead make MinValues a pointer, I think like this is easier to use for most people though.

2022-02-17 12:09 UTC, FedorLap2006 requested changes
Great PR! But this unfortunately will break any usage of current select menus.
How it might be solved:

- You can put a comment with a NOTE that you must specify 1 for the menu to be a single value select. 
- You can change it to pointer, that would be self-describing, and also will give the developers errors about usage of current implementation.

2022-02-17 12:09 UTC, FedorLap2006 commented
Also I think it would need additional feedback from the developers. So I'm going to hold it for a couple of days.

2022-02-20 04:53 UTC, plally commented
This was just the least likely fix to break stuff i could think off. I think we should move towards using pointers for all option fields in the future though.

2022-02-26 23:09 UTC, plally commented
this pr is no longer necessary

2022-02-26 23:09 UTC, closed without merging

2022-02-27 00:10 UTC, FedorLap2006 commented
Sorry, forgot to close it.