CI Test
bwmarrin/discordgo pull request #1076
Opened 2022-01-20 08:51 UTC by FedorLap2006

2022-01-20 20:41 UTC, FedorLap2006 commented
Okay, I think that's it, everything works. All that's left is to fix the tests and add the necessary linters.

2022-01-21 16:11 UTC, plally requested changes

2022-01-21 16:13 UTC, plally commented on .github/workflows/ci.yml
> +      - run: go test -v -race ./...
I think the only reason this works is go 1.15 is preinstalled on githubs ubuntu runners not because of your setup job

2022-01-22 21:57 UTC, FedorLap2006 commented on .github/workflows/ci.yml
> +      - run: go test -v -race ./...
You think so? Yea, I ran into some issues with checkouting in `setup`.

2022-02-16 13:24 UTC, FedorLap2006 commented
I think it's all done.

2022-02-16 13:24 UTC, merged