Add Invite Create/Delete
bwmarrin/discordgo pull request #1105
Opened 2022-02-24 18:58 UTC by pixelrazor

Fixes #1104 

I omitted the application object from the Invite, as it didn't already exist there anyways. If desired, I could refactor `MessageApplication` into the Application object, and add a ref to it in the invite

2022-02-24 18:59 UTC, pixelrazor commented on structs.go
> -	TargetUserType TargetUserType `json:"target_user_type"`
i couldn't see where they changed this in the change log, but this field has been renamed

2022-02-24 22:29 UTC, FedorLap2006 commented on structs.go
> +	InviteEmbeddedAppliction InviteTargetType = 2
```suggestion
	InviteTargetStream             InviteTargetType = 1
	InviteTargetEmbeddedAppliction InviteTargetType = 2
```

2022-02-25 20:33 UTC, FedorLap2006 requested changes

2022-02-25 20:33 UTC, FedorLap2006 commented on message.go
> +// of message objects
I'm not sure if this PR would be right place to add this comment

2022-02-25 20:33 UTC, FedorLap2006 commented on structs.go
> +	RedirectURIs *[]string `json:"-"`
Better to remove this field, since it doesn't have a purpose anymore.

2022-02-25 20:33 UTC, FedorLap2006 commented on structs.go
>  )
Since the type is meant to be renamed I think it would be fair to remove the old one.

2022-02-25 21:13 UTC, FedorLap2006 approved these changes

2022-02-25 21:13 UTC, FedorLap2006 commented
Thanks for the contribution!

2022-02-25 21:13 UTC, merged