feat: Add Guild Member Cover & Accent Color support
bwmarrin/discordgo pull request #1117
Opened 2022-02-27 17:23 UTC by 42Atomys

I will add Guild Member Cover & Accent Color support to the library 

Resolve #1093

2022-02-27 17:47 UTC, 42Atomys commented
Tested manually : works with static and animated user banner. 

@FedorLap2006 Ready for review

2022-02-28 15:42 UTC, FedorLap2006 commented on user.go
> +	// Banner the user's banner hash
```suggestion
	// The hash of the user's banner
```

2022-02-28 16:15 UTC, FedorLap2006 requested changes
Overall PR looks good to me, except a couple of things. Additionally, I see inconsistent naming of `cover` and `banner`. Please fix that.

2022-02-28 16:23 UTC, 42Atomys commented on user.go
> +	// see https://discord.com/developers/docs/reference#image-formatting
"Each" time a field is about image formatting, this link is provided (`structs.go#805` for example)

It's because is user ?

2022-02-28 16:49 UTC, 42Atomys commented on user.go
> +	// see https://discord.com/developers/docs/reference#image-formatting
I remove it

2022-02-28 17:30 UTC, FedorLap2006 requested changes

2022-02-28 17:30 UTC, FedorLap2006 commented on util.go
> +}
```suggestion
func bannerURL(bannerHash, staticBannerURL, animatedBannerURL, size string) string {
	var URL string
	if bannerHash == "" {
		return ""
	} else if strings.HasPrefix(bannerHash, "a_") {
		URL = animatedBannerURL
	} else {
		URL = staticBannerURL
	}

	if size != "" {
		return URL + "?size=" + size
	}
	return URL
}
```

2022-02-28 17:30 UTC, FedorLap2006 commented on structs.go
> +func (m *Member) BannerURL(size string) string {
Not sure if this would be necessary, since `Member` doesn't have `Banner` property

2022-02-28 22:02 UTC, FedorLap2006 commented
I'll give it a look tomorrow

2022-03-02 10:54 UTC, FedorLap2006 commented on structs.go
> +func (m *Member) BannerURL(size string) string {
I think it would be better to just implement it when it goes out. DiscordGo is 1:1 mapping, so if API doesn't have it, we don't as well.

2022-03-02 18:26 UTC, FedorLap2006 commented
Thank you for your contribution! Due to the fact that v0.24.0 is planned for today, I decided to make a couple of changes which I proposed to the PR myself. 

About the `Member.BannerURL` method, I think it would be best to implement it when it's going to be shipped. Additionally it would eliminate confusion on why it doesn't return customized guild banner.

2022-03-02 18:29 UTC, merged