Add dialer property in config
bwmarrin/discordgo pull request #1179
Opened 2022-05-06 22:01 UTC by uWynell

A little attempt to make this pull request.
Why would I need such an update? For example, if I would be able to pass custom `Dialer`, then I could use proxy ([click](https://stackoverflow.com/questions/33585587/creating-a-go-socks5-client)).
```go
dialSocksProxy, _:= proxy.SOCKS5("tcp", "proxy_ip", nil, proxy.Direct)
s, _:= discordgo.New("token")
s.Dialer = &websocket.Dialer{Dial: dialSocksProxy.Dial}
```
Sorry if I'm wrong. I'll be very happy to hear where exactly I made a mistake, if there's one.

2022-07-20 23:06 UTC, FedorLap2006 requested changes

2022-08-13 20:41 UTC, FedorLap2006 commented
Thanks for the contribution!

P.S. While ideally the voice (see the comment above) related changes should have been implemented here, I'll be adding them in a separate PR, since you have disabled maintainer edits on the branch.

2022-08-13 20:42 UTC, merged

2022-08-13 20:49 UTC, uWynell commented
Sorry for inactivity, I hadn't even logged into my account since this PR.

2022-08-13 20:55 UTC, FedorLap2006 commented
No problem, and as you can see, I've adressed it in the PR mentioned above.