Add files to MessageEdit
bwmarrin/discordgo pull request #1253
Opened 2022-09-30 08:04 UTC by ShadiestGoat

This PR adds the ability to edit the attachments of a message, following the discord API.

2022-09-30 08:05 UTC, ShadiestGoat commented on message.go
> +	Attachments *[]*MessageAttachment `json:"attachments,omitempty"`
I made this a pointer because an empty array doesn't mean it should be not specified in the json.

2022-09-30 14:10 UTC, ShadiestGoat commented
Forgot to mention: solves #1252

2022-09-30 21:49 UTC, FedorLap2006 requested changes

2022-09-30 21:49 UTC, FedorLap2006 commented on message.go
> +	Files []*File `json:"files,omitempty"`
Files are sent using `MultipartBodyWithJSON`, therefore should be omitted from the request.
```suggestion
	Files []*File `json:"-"`
```

2022-10-01 07:41 UTC, ShadiestGoat commented
@FedorLap2006 you're right, I changed it now

2022-10-03 23:07 UTC, FedorLap2006 approved these changes
LGTM. Though removing attachments won't work for now, since the `MultipartBodyWithJSON` encodes files a bit incorrectly.
I'll probably submit a fix for it soon.

2022-10-04 08:42 UTC, ShadiestGoat commented
I don't want to be "that guy", but would it be possible to know a possible timeline for this to be merged?

2022-10-07 11:47 UTC, merged

2022-10-07 11:48 UTC, FedorLap2006 commented
Thanks for your contribution!