Add fail_if_not_exists to MessageReference
bwmarrin/discordgo pull request #1376
Opened 2023-05-05 06:34 UTC by Earlopain

https://discord.com/developers/docs/resources/channel#message-reference-object

I wanted to make this a parameter of the `Reference` function where you can pass in false if needed. Go doesn't support default parameter values so I don't know how I should go about doing that. Any pointer are appreciated.

2023-05-11 13:18 UTC, FedorLap2006 requested changes

2023-05-11 17:46 UTC, Earlopain commented on message.go
>  func (m *Message) Reference() *MessageReference {
Thank you for the feedback, I implemented this new method. Because the type is now `*bool` I had to go with a somewhat awkward way of setting it.

2023-05-14 14:55 UTC, FedorLap2006 commented on message.go
>  func (m *Message) Reference() *MessageReference {
> somewhat awkward way of setting it.
While we expose `Reference` & `SoftReference` to the user for convenience and compatibility, we can implement it under the hood through a `reference(mustExist bool)` function. That way we avoid duplication and you can reference parameter variable directly.

2023-05-14 15:08 UTC, Earlopain commented on message.go
>  func (m *Message) Reference() *MessageReference {
Done, thanks again

2023-05-14 15:31 UTC, FedorLap2006 commented on message.go
> +// Reference returns a MessageReference of the given message
```suggestion
// Reference returns a MessageReference of the given message.
```

2023-05-14 15:45 UTC, FedorLap2006 approved these changes

2023-05-14 15:53 UTC, merged

2023-05-14 15:54 UTC, FedorLap2006 commented
Thanks for your contribution!