Add new permissions
bwmarrin/discordgo pull request #1411
Opened 2023-07-25 10:40 UTC by Earlopain

First commit makes the numbers bitflags which I find easier to parse and follows all the other flags in the repo. I also added docs for them.

Second commit adds missing flags currently documented at https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags

Third commit renames some fields to what they are now called on discords docs page.

Fourth commit adds currently undocumented flags, but there is a pending pr for those at https://github.com/discord/discord-api-docs/pull/6305

2023-11-16 15:28 UTC, Earlopain commented
The 2 permissions I added in the last commit are no longer undocumented, the PR for that has been merged.

2023-11-25 19:40 UTC, mrbentarikau commented
just a thought, maybe moving all these permissions from structs.go to a new file, like permissions.go?

2024-06-22 08:53 UTC, FedorLap2006 requested changes

2024-06-22 08:53 UTC, FedorLap2006 commented on structs.go
> +	PermissionManageServer = 1 << 5
```suggestion
	// Deprecated: PermissionManageServer has been replaced by PermissionManageGuild.
	PermissionManageServer = 1 << 5
	
	// Allows management and editing of the guild.
	PermissionManageGuild = 1 << 5
```

2024-06-22 08:53 UTC, FedorLap2006 commented on structs.go
> +	PermissionSendVoiceMessages = 1 << 46
`SEND_POLLS` and `USE_EXTERNAL_APPS` are not implemented

2024-06-22 14:08 UTC, FedorLap2006 requested changes

2024-06-22 14:08 UTC, FedorLap2006 commented on structs.go
> +	PermissionSendPools = 1 << 49
💧

2024-06-22 14:46 UTC, Earlopain commented on structs.go
> +	PermissionSendPools = 1 << 49
Eugh, thanks for catching this

2024-06-22 14:52 UTC, FedorLap2006 approved these changes

2024-06-22 14:52 UTC, FedorLap2006 commented on structs.go
> +	PermissionSendPools = 1 << 49
No problem! We all do this sometimes.

2024-06-22 14:53 UTC, merged