Update `UserGuilds()`
bwmarrin/discordgo pull request #1500
Opened 2024-02-27 14:46 UTC by hhaste

This PR adds support for the `with_count` query parameter on the `UserGuilds()` function. 

Additionally, the `limit` of returned guilds has been increased from 100 to 200.

Reference: https://discord.com/developers/docs/resources/user#get-current-user-guilds

2024-02-28 10:19 UTC, Earlopain commented
I think it would be better to add a new method `UserGuildsWithCounts` to not break current code. The old method can then just dispatch to the new one. Sad that go doesn't have default args...

You could also update struct member docs for `ApproximateMemberCount` and `ApproximatePresenceCount` since that doesn't currently mention this new way to obtain the information. Should probably switch that over to the methods you can call in discordgo for this instead of the verbatim copy from the discord api docs.

2024-02-28 10:38 UTC, hhaste commented
> I think it would be better to add a new method `UserGuildsWithCounts` to not break current code. The old method can then just dispatch to the new one.

There would be no `withCounts` argument on the `UserGuildsWithCounts` function, so having the old method dispatch to the new one wouldn't work. I could still make a new function, but I felt it would be redundant.

2024-02-28 11:03 UTC, Earlopain commented
Oh, right. Tbh, I don't know how this is usually handled, I haven't been around here for very long. @FedorLap2006 should be able to give some input there.

2024-03-03 01:10 UTC, FedorLap2006 commented
I think it would be better to make a breaking change, rather than introducing `UserGuildsWithCounts`.

2024-03-13 00:59 UTC, FedorLap2006 requested changes

2024-03-13 00:59 UTC, FedorLap2006 commented on restapi.go
> +// withCounts  : Whether to include approximate member and presence counts or not
```suggestion
// withCounts  : Whether to include approximate member and presence counts or not.
```

2024-03-13 00:59 UTC, FedorLap2006 commented on structs.go
> +	ApproximatePresenceCount int `json:"approximate_presence_count"`
```suggestion

	// Approximate number of members in this guild.
	// NOTE: this field is only filled when withCounts is true.
	ApproximateMemberCount int `json:"approximate_member_count"`

	// Approximate number of members in this guild.
	// NOTE: this field is only filled when withCounts is true.
	ApproximatePresenceCount int `json:"approximate_presence_count"`
```

2024-03-15 15:16 UTC, FedorLap2006 commented on structs.go
> +	// Approximate number of members in this guild.
```suggestion
	// Approximate number of non-offline members in this guild.
```

2024-03-15 15:21 UTC, FedorLap2006 approved these changes

2024-03-15 15:21 UTC, merged