updated go.mod go.sum files with new versions
bwmarrin/discordgo pull request #1537
Opened 2024-06-14 07:51 UTC by fuad-daoud

connecting to voice channel is stuck due to the changes in discord API which was fixed in versions 0.28.x just updated the example to use the new version

2024-06-20 08:48 UTC, FedorLap2006 requested changes

2024-06-20 08:48 UTC, FedorLap2006 commented on examples/voice_receive/go.mod
> +)
I'm not exactly sure where all these extra dependencies came from.
After running `go mod tidy` on `go.mod` with updated versions, it results only in:
```
module github.com/bwmarrin/discordgo/examples/voice_receive

go 1.22.4

require (
	github.com/bwmarrin/discordgo v0.28.1
	github.com/pion/rtp v1.6.0
	github.com/pion/webrtc/v3 v3.0.0-20200721060053-ca3cc9d940bc
)

require (
	github.com/gorilla/websocket v1.4.2 // indirect
	github.com/pion/randutil v0.1.0 // indirect
	golang.org/x/crypto v0.0.0-20210421170649-83a5a9bb288b // indirect
	golang.org/x/sys v0.0.0-20201119102817-f84b799fce68 // indirect
)
```

2024-07-06 08:50 UTC, fuad-daoud commented
removed extra packages.

2024-07-07 19:03 UTC, FedorLap2006 approved these changes

2024-07-07 19:04 UTC, merged