Add support for integration events
bwmarrin/discordgo pull request #1545
Opened 2024-07-13 11:43 UTC by Suhaibinator

Discordgo does not currently support Integration creates, updates, and deletes. This PR adds support for that.

See: 

Gateway intents (1 << 4) [Gatewat intents](https://discord.com/developers/docs/topics/gateway)
[Integrations](https://discord.com/developers/docs/topics/gateway-events#integration-create)

2024-07-13 11:46 UTC, Suhaibinator commented
@FedorLap2006

2024-07-28 10:12 UTC, FedorLap2006 requested changes

2024-07-28 10:12 UTC, FedorLap2006 commented on events.go
> +	*Integration
Payload also contains `guild_id`

2024-07-28 10:12 UTC, FedorLap2006 commented on events.go
> +	*Integration
`guild_id` is here too

2024-07-28 10:12 UTC, FedorLap2006 commented on events.go
> +	*Integration
The payload isn't an `Integration` object. Rather it's
```suggestion
    ID                   string `json:"id"`
    GuildID           string `json:"guild_id"`
    ApplicationID string `json:"application_id,omitempty"`
```

2024-07-28 10:12 UTC, FedorLap2006 commented on events.go
> +	*Integration
The payload isn't an `Integration` object. Rather it's
```suggestion
    ID string `json:"id"`
    GuildID string `json:"guild_id"`
    ApplicationID string `json:"application_id,omitempty"`
```
P.S. This is unformatted.

2024-07-28 14:13 UTC, Suhaibinator commented on events.go
> +	*Integration
Done

2024-07-28 14:13 UTC, Suhaibinator commented on events.go
> +	*Integration
Done

2024-07-28 14:15 UTC, Suhaibinator commented
@FedorLap2006 requested changes have been made

2024-07-29 10:00 UTC, FedorLap2006 approved these changes

2024-07-29 10:05 UTC, Suhaibinator commented
@FedorLap2006 do you know why it is saying that the format check failed?

Also it seems I am not able to merge the PR. Does the merge have to be performed by a maintainer?

2024-07-29 12:38 UTC, merged