Add User field to Interaction
bwmarrin/discordgo pull request #885
Opened 2021-03-01 12:49 UTC by Jleagle

2021-03-02 10:46 UTC, FedorLap2006 requested changes
Thanks, I think I just missed that thing when was making the PR. Glad you fixed this problem.

2021-03-02 10:46 UTC, FedorLap2006 commented on interactions.go
> +func (i Interaction) IsInGuild() bool {
Maybe `InGuild` would fit better?

2021-03-02 10:46 UTC, FedorLap2006 commented on interactions.go
> +// GetUser is a utility function for getting the User struct
Maybe I don't quite good speak on English... but "getting the User struct" - wouldn't be nicer to insert there instead of `getting`, `retrieving`?

2021-03-02 10:46 UTC, FedorLap2006 commented on interactions.go
> +	}
```suggestion
	if i.IsInGuild() {
		return i.Member.User
	}
```

2022-03-29 13:31 UTC, FedorLap2006 requested changes

2022-03-29 13:31 UTC, FedorLap2006 commented on structs.go
> +func (g Guild) IconURL() string {
```suggestion
func (g *Guild) IconURL() string {
```

2022-03-29 19:01 UTC, Jleagle commented
Conflicts sorted

2022-03-29 19:02 UTC, Jleagle commented
@FedorLap2006 Conflicts sorted

2022-03-30 21:15 UTC, FedorLap2006 requested changes
Aside from a couple of small issues, looks good to me. However I'm not really sure why you changed formatting in yaml files.

2022-03-30 21:15 UTC, FedorLap2006 commented on restapi.go
> +func (s *Session) GuildWithCounts(guildID string, withCounts ...bool) (st *Guild, err error) {
Since this is a separate function now, I think we can drop variadic arguments here.

2022-03-30 21:15 UTC, FedorLap2006 commented on restapi.go
> +// GuildWithCounts returns a Guild structure of a specific Guild.
```suggestion
// GuildWithCounts returns a Guild structure of a specific Guild with approximate member and presence counts.
```

2022-03-31 12:03 UTC, Jleagle commented
My IDE was complaining that the yamls had incorrect indents, i can revert?

2022-03-31 12:41 UTC, Jleagle commented
Done

2022-03-31 13:13 UTC, FedorLap2006 commented on restapi.go
> +//              uses variadic for backwards compatibility
```suggestion
```

2022-03-31 13:14 UTC, FedorLap2006 commented on restapi.go
> +func (s *Session) GuildWithCounts(guildID string, withCounts bool) (st *Guild, err error) {
Since this is already `WithCounts`, I think it would be best to just drop `withCounts`

2022-03-31 13:15 UTC, FedorLap2006 commented on restapi.go
> +		uri += "?" + queryParams.Encode()
```suggestion
		queryParams := url.Values{}
		uri += "?with_counts=true"
```

2022-03-31 14:25 UTC, FedorLap2006 requested changes

2022-03-31 14:25 UTC, FedorLap2006 commented on restapi.go
> +func (s *Session) GuildWithCounts(guildID string, withCounts bool) (st *Guild, err error) {
Since this function already retrieves guild with counts, I think it would be fair to drop `withCounts` parameter.

2022-03-31 14:25 UTC, FedorLap2006 commented on restapi.go
> +		uri += "?" + queryParams.Encode()
```suggestion
		uri += "?with_counts=true"
```

2022-03-31 19:10 UTC, FedorLap2006 commented on restapi.go
> +	body, err := s.RequestWithBucketID("GET", EndpointGuild(guildID)+"?"+queryParams.Encode(), nil, EndpointGuild(guildID))
```suggestion
	body, err := s.RequestWithBucketID("GET", EndpointGuild(guildID)+"?with_counts=true", nil, EndpointGuild(guildID))
```

2022-03-31 19:22 UTC, merged