Per-guild user avatars
bwmarrin/discordgo pull request #985
Opened 2021-08-02 02:59 UTC by vysiondev

Related to https://github.com/discord/discord-api-docs/pull/3081 and closes #965. I anticipate i'll have to update this as more info about per-guild user avatars are released/if they get added to the docs.

2021-08-21 17:57 UTC, CarsonHoffman commented
It seems as though your code was not run through `gofmt` before the commit (as Travis indicates). Please do so; this helps us keep our style consistent!

2021-12-13 03:04 UTC, Neoration commented
@CarsonHoffman Is there any update?

2021-12-14 23:54 UTC, CarsonHoffman requested changes

2021-12-14 23:54 UTC, CarsonHoffman commented on structs.go
> +	Avatar string `json:"avatar"`
`Avatar` is marked as nullable in the docs; it should probably be `*string` to avoid issues in unmarshaling.

2021-12-14 23:54 UTC, CarsonHoffman commented on user.go
> +	}
This seems to be backwards, no?

2022-03-23 18:54 UTC, FedorLap2006 commented
Closing in favor of https://github.com/bwmarrin/discordgo/pull/1077

2022-03-23 18:54 UTC, closed without merging